@startuml
class Logger {
    <<const>> - FileExtension : string = ".log"
    {static} <<readonly>> - LogBasePath : string
    - _logFilePath : string
    - _newFilePath : string
    + Dispose() : void
    + LogFormat(logType:LogType, context:Object, format:string, args:object[]) : void
    + LogException(exception:Exception, context:Object) : void
    + Init(name:string) : void
    + RenameLog(name:string) : void
}
class "AbstractSingleton`1"<T> {
}
"AbstractSingleton`1" "<Logger>" <|-- Logger
ILogHandler <|-- Logger
IDisposable <|-- Logger
Logger o-> "_defaultLogHandler" ILogHandler
Logger --> "_streamWriter" StreamWriter
@enduml
