@startuml
class CarViewController {
    <<const>> - MissionStateKey : string = "SubState"
    - Awake() : void
    - Start() : void
    - OnDisable() : void
    +  <<event>> ReloadedEvent : Action 
    - LoadMission(mission:MissionSo) : void
    - CompleteMission() : void
    - SwitchSubStateView(obj:IListItemData) : void
}
class "ListController`1"<T> {
}
MonoBehaviour <|-- CarViewController
CarViewController --> "actionItemTemplate" VisualTreeAsset
CarViewController --> "_actionListController<MissionSubState>" "ListController`1"
CarViewController --> "_confirmButton" Button
CarViewController --> "_csvLogger" CSVLogger
CarViewController --> "_mainImage" Image
@enduml
