@startuml
class "ListController`1"<T> {
    + ListController(root:VisualElement, itemTemplate:VisualTreeAsset, name:string)
    + Dispose() : void
    +  <<event>> ItemSelectedEvent : Action<IListItemData> 
    - ConfigureListView() : void
    + UpdateList(newItems:IEnumerable<T>) : void
    + AddItem(item:T) : void
    + RemoveItem(item:T) : bool
    + Clear() : void
    - RefreshListView() : void
    + SelectItem(idx:int) : void
    + SelectItem(item:T) : void
    + GetSelectedItem() : T
    - OnItemSelected(enumerable:IEnumerable<object>) : void
}
class "List`1"<T> {
}
IDisposable <|-- "ListController`1"
"ListController`1" --> "_itemTemplate" VisualTreeAsset
"ListController`1" o-> "_listData<T>" "List`1"
"ListController`1" --> "_listView" ListView
@enduml
