@startuml
class Street {
    - Start() : void
    - OnDestroy() : void
    - OnDrawGizmos() : void
    - OnValidate() : void
    - GetDependencies() : void
    - {static} GetWorldPointAtIndex(container:SplineContainer, index:int) : Vector3
    - GetWorldPointAtIndex(lane:Lane, idx:int) : Vector3
    - GetKnotAtIndex(lane:Lane, idx:int) : BezierKnot
    - GetLane(lane:Lane) : SplineContainer
}
enum Lane {
    LaneA,
    LaneB,
}
class "List`1"<T> {
}
class Exit {
    + DrawGizmos(laneA:SplineContainer, laneB:SplineContainer) : void
}
struct Address {
    + idx : int
    + Equals(other:Address) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
    + GetKnot() : BezierKnot
    + GetWorldPoint() : Vector3
    + GetSpline() : SplineContainer
}
class "IEquatable`1"<T> {
}
MonoBehaviour <|-- Street
Street --> "lane1" SplineContainer
Street --> "lane2" SplineContainer
Street o-> "exits<Vector2Int>" "List`1"
Street o-> "exitLanes<Exit>" "List`1"
Street --> "lane1Material" Material
Street --> "lane2Material" Material
Street --> "spline1" Spline
Street --> "spline2" Spline
Street +-- Lane
Street +-- Exit
Exit --> "myAddress" Address
Exit o-> "targets<Address>" "List`1"
Street +-- Address
"IEquatable`1" "<Address>" <|-- Address
Address --> "street" Street
Address --> "lane" Lane
@enduml
