@startuml
hide empty members
hide interface
remove MonoBehaviour
remove ScriptableObject
remove VisualTreeAsset
remove Texture2D
remove VectorImage
remove Image
remove Label
remove VisualElement

!include .\\Scripts\HumanInputObserver.puml
!include .\\UI\ListController.puml
!include .\\UI\CarView\CarViewController.puml
!include .\\UI\CarView\CarViewManager.puml
!include .\\UI\CarView\ContentController.puml
!include .\\UI\ListItem\IListItemData.puml
!include .\\UI\ListItem\ListItemController.puml
@enduml
