@startuml
class CarManager {
    - Awake() : void
    + AddCar(car:ADSV_AI) : void
    + RemoveCar(id:int) : void
    + GetCar(id:int) : ADSV_AI
}
class "Dictionary`2"<T1,T2> {
}
MonoBehaviour <|-- CarManager
CarManager o-> "_cars<int,ADSV_AI>" "Dictionary`2"
@enduml
