@startuml
class GameManager {
    - gameSpeedEasy : float = 5
    - gameSpeedHard : float = 1
    - maxMissions : int = 10
    - missionsToComplete : int = 20
    - _currentGameSpeed : float
    - _lastMissionCreationTime : float
    - Start() : void
    - FixedUpdate() : void
    - OnDisable() : void
    - OnGameRestart() : void
    - SwitchScene(scene:GameplayGlobals.Scenes) : void
    - UpdateMissionQueue() : void
    - SetGameMode(id:int, inputMethod:GameplayGlobals.Input, severity:GameplayGlobals.Severity) : void
}
MonoBehaviour <|-- GameManager
GameManager --> "_logger" Logger
GameManager --> "_missionManager" MissionManager
@enduml
