@startuml
class MissionDataLoader {
    - OnDisable() : void
    - OnValidate() : void
    {static} - TryParseMissionName(fullName:string, path:string[]) : bool
    + CreateMissionTemplates() : void
}
class "ScriptableSingleton`1"<T> {
}
class "SerializedDictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
"ScriptableSingleton`1" "<MissionDataLoader>" <|-- MissionDataLoader
MissionDataLoader o-> "_textures<string,Texture2D>" "SerializedDictionary`2"
MissionDataLoader o-> "missions<MissionSo>" "List`1"
MissionDataLoader --> "textures<string,Texture2D>" "SerializedDictionary`2"
@enduml
