@startuml
class MissionSo {
    - _timeEnd : float
    - _timeLoaded : float
    - _timeStart : float
    - OnValidate() : void
    + Equals(other:IListItemData) : bool
    + mainText : string <<get>>
    + supportText : string <<get>> = null
    + approximateHeight : int <<get>>
    + GetRouteTexture() : Texture2D
    + Start() : void
    + Load() : void
    + <<virtual>> Complete(missionSubState:MissionSubState) : bool
    + SyncLists() : void
    + GenerateStates() : void
}
class "List`1"<T> {
}
ScriptableObject <|-- MissionSo
IListItemData <|-- MissionSo
MissionSo --> "route" Texture2D
MissionSo o-> "subStates<MissionSubState>" "List`1"
MissionSo --> "map" Texture2D
MissionSo --> "_icons" IconAtlas
MissionSo --> "options<MissionSubState>" "List`1"
MissionSo --> "leftImage" VectorImage
MissionSo --> "rightImage" VectorImage
@enduml
