@startuml
class MissionController {
    - _activeMission : int
    + inProgress : bool <<get>>
    + TryActivateMission() : bool
}
class "List`1"<T> {
}
MonoBehaviour <|-- MissionController
MissionController --> "missions<Mission>" "List`1"
@enduml
