@startuml
abstract class BetterScriptableObject {
    - OnValidate() : void
    # {abstract} HandleChanged() : void
    +  <<event>> OnChanged : Action 
}
ScriptableObject <|-- BetterScriptableObject
@enduml
