@startuml
abstract class EditorBehavior {
    # Dirty : bool
    - Update() : void
    - OnValidate() : void
    # {abstract} HandleIsDirty() : void
    # {abstract} RefreshComponents() : void
}
MonoBehaviour <|-- EditorBehavior
@enduml
