@startuml
class MissionSo {
    - correctSubState : int
    - OnValidate() : void
    + Equals(other:IListItemData) : bool
    + mainText : string <<get>>
    + supportText : string <<get>> = null
    + approximateHeight : int <<get>>
    + GetRouteTexture() : Texture2D
    - SyncLists(images:Dictionary<string, Texture2D>) : void
    + Complete(missionSubState:MissionSubState) : bool
}
class "List`1"<T> {
}
ScriptableObject <|-- MissionSo
IListItemData <|-- MissionSo
MissionSo o-> "EmergencyState" MissionSubState
MissionSo --> "route" Texture2D
MissionSo o-> "subStates<MissionSubState>" "List`1"
MissionSo --> "map" Texture2D
MissionSo --> "_icons" IconAtlas
MissionSo --> "options<MissionSubState>" "List`1"
MissionSo --> "leftImage" VectorImage
MissionSo --> "rightImage" VectorImage
@enduml
