@startuml
class ServiceLocator {
    + TryRegister(service:object) : bool
    + TryGet(service:T) : bool
}
class "AbstractSingleton`1"<T> {
}
class "ConcurrentDictionary`2"<T1,T2> {
}
"AbstractSingleton`1" "<ServiceLocator>" <|-- ServiceLocator
ServiceLocator o-> "_services<Type,object>" "ConcurrentDictionary`2"
@enduml
