@startuml
hide empty members
remove MonoBehaviour
remove ScriptableObject
remove VisualTreeAsset
hide interface

!include .\\DebugCharacterController.puml
!include .\\car logic\AbstractFollower.puml
!include .\\car logic\ADSV_AI.puml
!include .\\car logic\BaseStateMachine.puml
!include .\\car logic\CarTarget.puml
!include .\\car logic\NavigationProvider.puml
!include .\\car logic\NavMeshCaster.puml
!include .\\car logic\NavMeshFollower.puml
!include .\\car logic\PathVisualizer.puml
!include .\\car logic\SplineAbstractFollower.puml
!include .\\Gameplay\CarManager.puml
!include .\\Gameplay\Mission.puml
!include .\\Gameplay\MissionController.puml
!include .\\Gameplay\PrefabGrid.puml
!include .\\Gameplay\StreetEvent.puml
!include .\\Streets\JunctionTrigger.puml
!include .\\Streets\Street.puml
!include .\\Streets\StreetManager.puml
!include .\\Streets\StreetNet.puml
!include .\\UI\ColorGuide.puml
!include .\\UI\DynamicGrid.puml
!include .\\UI\GUIUtils.puml
!include .\\UI\IconAtlas.puml
!include .\\UI\IListElement.puml
!include .\\UI\IPlayerClickable.puml
!include .\\UI\ISubScreen.puml
!include .\\UI\ModalUI.puml
!include .\\UI\VideoFeed.puml
!include .\\Utils\Logger.puml
!include .\\Utils\SplineHelper.puml
!include .\\Utils\TransformUtility.puml
!include .\\Utils\Editor\CameraStackSynchronizer.puml
!include .\\Utils\Editor\NavMeshSnap.puml
!include .\\Utils\Lucide\GlyphData.puml
!include .\\Utils\Lucide\LucideLoader.puml
!include .\\Utils\Objects\ObjectManagementUtility.puml
!include .\\Utils\Objects\ServiceLocator.puml
!include .\\Utils\Objects\WeightedPool.puml
!include .\\Utils\Types\AbstractSingleton.puml
!include .\\Utils\Types\BetterScriptableObject.puml
!include .\\Utils\Types\EditorBehavior.puml
!include .\\Utils\Types\IState.puml
@enduml
