@startuml
abstract class "BaseStateMachine`1"<T> {
    - _state : T
    - _lastMsgMillis : float
    # stateChanged : bool <<get>>
    - previousState : T <<get>> <<set>>
    + state : T <<set>> <<get>>
    +  <<event>> OnStateChangeEvent : Action<T> 
    # BaseUpdate() : void
    # PrintState() : void
    # PrintEntryState() : void
    # PrintExitState() : void
}
MonoBehaviour <|-- "BaseStateMachine`1"
@enduml
