@startuml
class CarTarget {
    + pull : float = 100
    + maxDistance : float = 50
    - _junctionError : bool
    - _recursionLock : bool
    + distance : float <<get>>
    - Awake() : void
    - Update() : void
    - ResetPosition() : void
}
MonoBehaviour <|-- CarTarget
CarTarget --> "follower" Transform
CarTarget --> "splineFollower" SplineAnimate
@enduml
