@startuml
abstract class NavigationProvider {
    + baseSpeed : float
    + visualize : bool = true
    + {abstract} GetTargetSpeed() : float
    + {abstract} SetTargetSpeed(speed:float) : void
    + {abstract} SetTargetLocation(position:Vector3) : void
    + {abstract} Halt() : void
}
MonoBehaviour <|-- NavigationProvider
@enduml
