@startuml
class GlyphData {
    + iconID : int
    + unicodeString : string
    + {static} UnicodeToChar(hex:string) : string
    + {static} UnicodeToChar(code:int) : string
    # <<override>> HandleChanged() : void
}
BetterScriptableObject <|-- GlyphData
@enduml
