@startuml
class IconAtlas {
    + resourcesFolder : string
    - _isRebuilt : bool
    - OnEnable() : void
    - OnDisable() : void
    + Build() : void
}
class "SerializedDictionary`2"<T1,T2> {
}
ScriptableObject <|-- IconAtlas
IconAtlas o-> "cache<string,VectorImage>" "SerializedDictionary`2"
@enduml
