@startuml
interface IListItemData {
    + mainText : string <<get>>
    + supportText : string <<get>>
    + approximateHeight : int <<get>>
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<IListItemData>" <|-- IListItemData
IListItemData --> "leftImage" VectorImage
IListItemData --> "rightImage" VectorImage
@enduml
