@startuml
class ListItemController {
    + LoadVisualElement(visualElement:VisualElement) : void
    + SetData(data:IListItemData) : void
    {static} - UpdateIcon(target:Image, icon:VectorImage, group:string) : void
}
ListItemController --> "_leftImage" Image
ListItemController --> "_mainText" Label
ListItemController --> "_rightImage" Image
ListItemController --> "_supportText" Label
@enduml
